repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v18.1.6' 
    hooks:
      - id: clang-format
        args:
          - --style=google
        files: \.(c|h|cpp|hpp|cc)$
